apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
    - name: branch
      description: the branch for the git repo
      default: "master"
    - name: inventoryRepo
      description: The variable storing git integration for the repository storing build inventory with the toolchain
    - name: apikey
      description: the ibmcloud api key
    - name: registryNamespace
      description: the ibmcloud registry namespace
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: registryRegion
      description: the ibmcloud registry region
      default: us-south
    - name: clusterRegion
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: clusterNamespace
      description: The Kubernetes cluster namespace
      default: prod
    - name: appName
      description: application name
    - name: imageName
      description: image name
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: pipeline-build-task
      taskRef:
        name: build-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: registryNamespace
          value: $(params.registryNamespace)
        - name: registryRegion
          value: $(params.registryRegion)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: pipeline-validate-task
      runAfter: [pipeline-build-task]
      taskRef:
        name: validate-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: registryRegion
          value: $(params.registryRegion)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: pipeline-clone-inventory-task
      runAfter: [pipeline-validate-task]
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "toolchain-apikey"
        - name: repository
          value: $(params.inventoryRepo)
        - name: branch
          value: "master"
        - name: apikey
          value: $(params.apikey)
        - name: appname
          value: $(params.appName)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: git-credentials-json-file
          value: credentials.json
      workspaces:
      - name: output
        workspace: pipeline-pvc
        subpath: inventory-repo
